# Generated by Django 2.1.1 on 2018-09-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('form_type', models.CharField(choices=[('rectangle', 'Rectangle'), ('ellipse', 'Ellipse')], default='rectangle', max_length=50)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
    ]
