# Generated by Django 2.0 on 2018-09-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_customer', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReserverDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserver', models.DateField()),
            ],
            options={
                'ordering': ('-date_reserver',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='reserve_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_today', to='orders.ReserverDay'),
        ),
        migrations.AddField(
            model_name='order',
            name='tables',
            field=models.ManyToManyField(related_name='orders', to='tables.Table'),
        ),
    ]
